language: python
python:
  - "3.6"
  
install:
  - pip install -r requirements.txt
  - python setup.py install
  - chmod 744 $(HOME)/virtualenv/python3.6.7/



before_script:
  - eggpath='$HOME/virtualenv/python3.6.7/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/bin'
  - chmod 744 $eggpath/ch_line_ending.py $eggpath/create_consensus_network.py $eggpath/sjaracne.exe

script: python -m pytest -v
    
#blocklist
branches:
  except:
  - develop
  - SJARACNE-Internal-legacy
  - master
#safelist
branches:
  only:
  - cwl

notifications:
  email: false
