language: python
python:
  - "3.6"
  
install:
  - pip install -r requirements.txt

script: pytest
    
#blocklist
branches:
  except:
  - develop
  - SJARACNE-Internal-legacy
  - master
#safelist
branches:
  only:
  - cwl


notifications:
  email: false
