language: python
python:
  - "3.6"
  
install:
  - pip install -r requirements.txt

script: ./tests/test_ch_line_ending.py
script: ./tests/test_create_consensus_network.py
    
#blocklist
branches:
  except:
  - develop
  - SJARACNE-Internal-legacy
  - master
#safelist
branches:
  only:
  - cwl


notifications:
  email: false
