language: python
python:
  - "3.6"
  
install:
  - pip install -r requirements.txt
  - python setup.py install

script: python -m pytest
    
#blocklist
branches:
  except:
  - develop
  - SJARACNE-Internal-legacy
  - master
#safelist
branches:
  only:
  - cwl

notifications:
  email: false
